import { FormArray, FormControl } from '@angular/forms';

export interface ICapstone {
  userId: string,
  ContactName: string,
  ContactPhone: string,
  ContactEmail: string,
  JobTitle: string,
  CompanyName: string,
  Address: string,
  Website: string,
  ProjectTitle: string,
  Description: string,
  Requirements: string,
  MileStone1: string,
  MileStone2: string,
  Milestone3: string,
  BenefitStudent: string,
  BenefitSponsor: string,
  Provide: string,
  Skill0: string,
  Skill1: string,
  Skill2: string,
  Skill3: string,
  Skill4: string,
  Skill5: string,
  Skill6: string,
  Skill7: string,
  Skill8: string,
  Skill9: string,
  RequireNDA: string,
  RetainIP: string,
  WorkonSite: string,
  SponsorSitePresentation: string,
  CampusPresentation: string,
  VideoPresentation: string,
  NumberofTeams: string,
  sixToNineVirtual: string,
  sixToNineInPerson: string,
  nineToTwelveVirtual: string,
  nineToTwelveInPerson: string,
  twelveToThreeVirtual: string,
  twelveToThreeInPerson: string,
  threeToFiveVirtual: string,
  threeToFiveInPerson: string,
  AdditionalAvailability: string,
  DateEntered: Date
}